### PR TITLE
Update for Chapter 10 "tools we like"

### PR DESCRIPTION
**Pull request by EDRi-org**
This commit proposes an update to the list of apps we recommend for kids. I have replaced some outdated examples such as APG with more current replacements such as OpenKeychain. I have also added Firefox as a browser and moved Tor a little down the list. I have removed Chatsecure and honestly would also like to propose to remove Pidgin. Not sure we encourage kids to use more privacy-friendly apps with their friends by recommending XMPP. If you really _want_ to keep XMPP it, please re-add Chatsecure, but also add Conversations (for Android) and replace OTR with the more modern OMEMO.

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
Did you have a look at the proposals in #2 and #4 

As for XMPP and OTR, I believe OMEMO is better than OTR for XMPP, but suspect XMPP is too hard to set up compared to the alternatives.

**Comment by EDRi-org** [comment]
I agree with #2 and think I replaced Jitsi Desktop with Jitsi Meet (that's how the WebRTC-based web app is called now).

As for #4, I have used Jami a while ago when it was still called Ring but found it drained my phone battery due to the p2p connections it needed to maintain. Not sure if that is better now as I haven't tried it since. I guess it comes down to whether we would like to recommend more niche products because they tick some boxes (decentralised, no phone number needed), or whether we prefer to recommend more widely used solutions such as Signal. Because in terms of functionality I don't see any advantage of Jami over Signal. But am happy to learn.

**Comment by petterreinholdtsen** [comment]
Good to know you were aware of both issues.  I suggest we discuss the merits of Jami in #4.  I do not know its power drain on mobile phones, as I do not want to own a mobile phone.  On linux, though, it work better than Signal when it comes to video and audio calls, which Signal Desktop do not provide.

**Review by bfg1981 — COMMENTED** [review]
I am unable to adequately review these changes.

**Comment by EDRi-org** [comment]
Okay, let me know if you have any additional questions on this list before merging. I think this should really be the list to be used in other language versions too before printing as the previous one has outdated/unmaintained apps on it.

**Comment by petterreinholdtsen** [comment]
I just came across <URL: https://securechatguide.org/applist.html > with a lot of alternatives for secure communication.   Thought it best to share it here.

If no-one want to decide if the proposal @EDRi-org is good or not, what about just accepting it and improve it in the next pull request if it need to be improved?

**Comment by xenadu000** [comment]
On Sun, 1 Sep 2019, petterreinholdtsen wrote:

> I just came across <URL: 
> https://securechatguide.org/applist.html > with a lot of 
> alternatives for secure communication.  Thought it best to 
> share it here.

Good!

> If no-one want to decide if the proposal @EDRi-org is good or 
> not, what about just accepting it and improve it in the next 
> pull request if it need to be improved?

I vote for that course of action, i e accepting it.

Thomas Gramstad

**Comment by petterreinholdtsen** [comment]
The changes are now in en.txt.  Please review and make new pull requests for any further changes.  It would be easier if each individual change was its own pull request, to be able to discuss the merit of each replacement/addition individually.

**Pull request merged**
